# Generated by Django 5.1.7 on 2025-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricle', models.CharField(max_length=100, verbose_name='matricule')),
                ('modele', models.CharField(max_length=250, verbose_name='modele')),
                ('dernier_vidange', models.DateField(verbose_name='dernier_vidange')),
                ('killometrage', models.FloatField(verbose_name='killometrage')),
            ],
        ),
    ]
