# Generated by Django 5.1.7 on 2025-03-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='matricle',
            new_name='matricule',
        ),
    ]
