# Generated by Django 5.1.7 on 2025-03-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='membre',
            new_name='membres',
        ),
    ]
