# Generated by Django 5.1.7 on 2025-03-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_rename_membre_membres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='membres',
            new_name='bookstore',
        ),
    ]
